woowa-techcamp-2020/bmart-5

.eslintrc.json, .gitignore, .prettierrc, .vscode/settings.json, client/tsconfig.json, package-lock.json, package.json, server/tsconfig.json, shared/.env.sample, tsconfig.json
- 부모 tsconfig.json, client, server tsconfig.json
- .env, .env.sample
- .gitignore
- prettier
- eslint (prettier 옵션 포함)
- vscode setup
- resolve #6
- 🔗 [타이스크립트](https://github.com/woowa-techcamp-2020/bmart-5/wiki/%EA%B8%B0%EC%88%A0-%EA%B3%B5%EC%9C%A0#%ED%83%80%EC%9E%85%EC%8A%A4%ED%81%AC%EB%A6%BD%ED%8A%B8)
- 🔗 [prettier](https://github.com/woowa-techcamp-2020/bmart-5/wiki/%EA%B8%B0%EC%88%A0-%EA%B3%B5%EC%9C%A0#prettier)
- 🔗 [eslint](https://github.com/woowa-techcamp-2020/bmart-5/wiki/%EA%B8%B0%EC%88%A0-%EA%B3%B5%EC%9C%A0#prettier)
=> feat: 공통 설정 파일 초기화 #6

client/package-lock.json, client/package.json, client/src/App.tsx, client/src/components/Header/index.tsx, client/src/index.tsx, client/src/pages/MainPage/index.tsx
> 스타일드컴포넌트 설치 및 세팅
> 리액트 타입 변경 (FunctionComponent -> React.FC)
> 임시 스타일 헤더 생성
- resolve #10
=> chore: 스타일드컴포넌트 세팅#10

client/craco.config.js, client/package.json, client/src/App.tsx, client/src/pages/MainPage/index.tsx, client/tsconfig.json, client/tsconfig.paths.json, client/yarn.lock
> craco를 설치해서 CRA환경에서도 '@디렉토리명' 처럼 절대 경로 이용가능
- resolve #54
=> chore: craco 이용해서 절대경로 세팅#54

server/package.json, server/src/config/consts.ts, server/src/config/express.ts, server/src/controllers/index.ts, server/src/main.ts, server/src/models/category.ts, server/src/models/index.ts, server/src/models/product.ts, server/src/models/sub-category.ts, server/src/modules/database/connection.ts, server/src/modules/database/database.ts, server/src/modules/database/db-service.ts, server/src/modules/database/index.ts, server/src/routers/index.ts, server/yarn.lock, shared/.env.sample
- category, sub_category, product 모델링
- sequelize connection 설정
- db migrate 옵션 env 추가
- model - controller - router 구조 설정
- resolve #18
🔗 [sequelize typescript 공홈](https://sequelize.org/master/manual/typescript.html)
=> Connect mysql#19

client/create_react_component.sh
현재 컴포넌트 구조에 따른 컴포넌트 자동 생성 스크립트를 작성하였습니다.
- ./create_react_components.sh [단위 이름] [컴포넌트 이름]으로 컴포넌트 자동 생성 가능
- ex) ./create_react_components.sh modules Modal
- resolve #56 
=> chore: react 컴포넌트 자동 생성 스크립트 작성 #56

client/src/App.tsx, client/src/components/modules/ProductDetailInfo/ProductDetailInfo.spec.tsx, client/src/components/modules/ProductDetailInfo/ProductDetailInfo.tsx, client/src/components/modules/ProductDetailInfo/index.tsx, client/src/components/modules/ProductDetailInfo/styled.tsx, client/src/pages/ProductPage/ProductPage.tsx, client/src/pages/ProductPage/index.tsx, client/src/utils/constants.tsx
ProductDetailInfo 컴포넌트를 만들었습니다.
- ProductPage를 추가해서 /product 에서 볼 수 있습니다.
- 개략적으로 만들어 나중에 추가로 작업해야합니다.
- 배달 정보에서 스티커 같은 요소 구현
- 배달 정보에서 시간 부분만 bold 처리
- resolve #42 
=> feat: ProductDetailInfo 컴포넌트 구현 #42

client/package.json, client/src/components/modules/ListLoading/ListLoading.tsx, client/src/components/modules/ListLoading/index.tsx, client/src/components/modules/ListLoading/styled.tsx, client/src/components/modules/ProductCard/ProductCard.tsx, client/src/components/modules/SlidableContainer/SlidableContainer.tsx, client/src/utils/API.tsx, client/src/utils/constants.tsx, client/tsconfig.paths.json, client/yarn.lock, shared/dto/index.ts, shared/dto/product-dto.ts
- 리스트 로딩 컨테이너 초안 작성
- API base meta data 초기화
- LatestProductsLimit, baseURL 상수 추가
- 절대경로 shared 추가
- product-dto response 추가
- http-status 모듈 사용
- product click event 초안 작성
- useEffect api call
- react start script 80포트로 시작으로 변경
- node 서버 시작시  .env 3000번 포트로 변경 필요
- resolve #70
🔗 [use effect async 사용](https://www.robinwieruch.de/react-hooks-fetch-data)
🔗 [리스트 로딩 컴포넌트](https://www.smashingmagazine.com/2020/06/rest-api-react-fetch-axios/)
🔗 [블러 필터](https://webisfree.com/2019-07-09/css-filter-%ED%94%84%EB%A1%9C%ED%8D%BC%ED%8B%B0-%EC%82%AC%EC%9A%A9%ED%95%98%EC%97%AC-%EB%B8%94%EB%9F%AC-%ED%9A%A8%EA%B3%BC-%EC%A0%81%EC%9A%A9%ED%95%98%EA%B8%B0-blur)
=> Fetch product#70

.github/workflows/main.yml, appspec.yml
Woowa AWS에 필요한 권한들을 추가한 뒤, github action 스크립트와 appspec을 작성하였습니다.
master에 push 되었을 때 실행되므로, master 브랜치로 머지된 후 정상 동작하는지 테스트 해야합니다.
🔗 [Using Github Actions to run automated tests and deployment to AWS EC2 with CodeDeploy.](https://otseobande.com/using-github-actions-to-run-automated-tests-and-deployment-to-aws-ec2-with-codedeploy-ck6pkjkk202r7dfs1wddwa1l5)
🔗 [1) AWS로 배포하기 시리즈 - 1. Code Deploy 사용하기](https://jojoldu.tistory.com/281?category=777282)
🔗 [github action과 aws code deploy를 이용하여 spring boot 배포하기](https://isntyet.github.io/deploy/github-action%EA%B3%BC-aws-code-deploy%EB%A5%BC-%EC%9D%B4%EC%9A%A9%ED%95%98%EC%97%AC-spring-boot-%EB%B0%B0%ED%8F%AC%ED%95%98%EA%B8%B0(1)/)
🔗 [Github Action을 이용해서 React 프로젝트 S3에 …
=> feat: github action 자동배포 스크립트 작성 #20

client/scripts/bulk_create_all.sh, client/scripts/bulk_create_category.sh, client/scripts/bulk_create_product.sh, client/scripts/bulk_create_sub_category.sh, client/scripts/data/fruits.txt, client/scripts/data/vegetables.txt, server/src/config/constants.ts, server/src/config/express.ts, server/src/controllers/product-controller.ts, server/src/controllers/sub-category-controller.ts, server/src/models/category.ts, server/src/models/product.ts, server/src/models/sub-category.ts, server/src/routers/product-router.ts, server/src/routers/sub-category-router.ts
- category, sub_category orderWeight nullable하게 설정
- product imgUrl 프로퍼티 생성
- 각 모델 bulkCreate api 작성
- bulk_create_all.sh : category, sub_category, product 순서로 스크립트 체이닝
- bulk_create_category.sh : 서비스에 필요한 카테고리 생성 스크립트
- bulk_create_sub_category.sh : 서비스에 필요한 하위 카테고리 생성 스크립트
- bulk_create_product.sh : data 폴더에 있는 쿠팡 데이터 txt파일을 읽어서 상품 데이터 생성
- resolve #12
🔗 [csv to txt with other delimeter](https://onlinecsvtools.com/change-csv-delimiter)
🔗 [bodyParser 리미트 옵션](https://blog.naver.com/dlaxodud2388/222007509565)
=> Fetch mock data#12

.github/workflows/main.yml, .gitignore, appspec.yml, client/package.json, deploy.sh
github actions를 사용해 자동 배포할 수 있는 스크립트를 추가하였습니다.
이후 master에 PR하고, 머지하여 테스트합니다.
- resolve #20
=> feat: github actions 자동 배포 스크립트 작성 #20

.gitignore, client/src/components/modules/CategoryContainer/CategoryContainer.tsx, client/src/components/modules/CategoryContainer/index.tsx, client/src/components/modules/SlidableContainer/SlidableContainer.tsx, client/src/components/modules/SlidableContainer/index.tsx, client/src/pages/index.tsx, client/src/pages/temp/index.tsx, client/tsconfig.json
> Next.js에 맞게 fetch를 변경함.
> useEffect를 제거하고 props로 fetch한 데이터를 받아옴.
- resolve #83
=> refactor : Next.js fetch 설정

.github/workflows/main.yml
배포 브랜치를 develop으로 설정합니다.
- resolve #89
=> chore: 배포 브랜치 develop으로 변경 #89

.github/workflows/main.yml
client 디렉토리에서 build하도록 수정하였습니다.
- resolve #91
=> fix: client 디렉토리에서 build 하도록 수정 #91

client/scripts/create_react_component.sh
경로가 script 디렉토리로 변경되어 스크립트가 정상 동작하지 않는 문제를 해결했습니다.
- resolve #97
=> fix: create_react_component 경로 오류 수정 #97

client/.storybook/main.js, client/.storybook/preview.js, client/.storybook/webpack.config.js, client/package.json, client/src/components/atoms/Icon/Icon.stories.tsx, client/src/components/atoms/Icon/Icon.tsx, client/src/components/atoms/Logo/Logo.stories.tsx, client/src/components/atoms/Logo/Logo.tsx, client/src/components/modules/Header/Header.stories.tsx, client/src/components/modules/Header/Header.tsx, client/yarn.lock
StoryBook을 설치하고, Icon, Logo, Header에 대한 예시 스토리들을 추가하였습니다.
- tsconfig의 경로를 인식하는 문제를 해결하는데 어려움이 있었습니다.
- 아래 링크로 해결하였습니다.
🔗 [문제 해결 방법](https://github.com/storybookjs/storybook/issues/3916#issuecomment-664349094)
- client 디렉토리에서 `yarn install` 후 `yarn run storybook` 으로 storybook을 실행할 수 있습니다.
- resolve #102 
=> env: Storybook setup #102

client/package.json, client/src/components/modules/ListLoading/ListLoading.tsx, client/src/components/modules/ProductCard/ProductCard.tsx, client/src/components/modules/ToastModal/ToastModal.tsx, client/src/components/templates/SlidableContainer/SlidableContainer.tsx, client/src/components/templates/TabViewContainer/TabViewContainer.tsx, client/src/pages/index.tsx
- ProductCard의 Props 형태가 달라지면서 발생하는 문제 해결
- 사용하지 않는 함수와 인자 제거.
- ListLoading 추후에 확인 필요.
- resolve #107 
🔗 [링크](url)
=> fix: 프론트 에러 수정#107

client/src/commons/Layout/Layout.tsx, client/src/commons/styles/Normalize.tsx, client/src/components/atoms/CounterBtn/CounterBtn.tsx, client/src/components/atoms/CounterBtn/styled.tsx, client/src/components/modules/CategoryIcon/styled.tsx, client/src/components/modules/Header/Header.tsx, client/src/components/modules/Header/styled.tsx, client/src/components/modules/ProductCard/styled.tsx, client/src/components/modules/ToastModal/styled.tsx, client/src/components/templates/CategoryContainer/CategoryContainer.tsx, client/src/components/templates/CategoryContainer/styled.tsx
미디어 쿼리 이용해서 사이즈를 조절해보았다.
폰트 사이즈는 rem으로 맞췄다.
- resolve #105 
🔗 [링크](url)
=> feat: 미디어쿼리 이용 사이즈 조절#105

client/src/commons/styles/Normalize.tsx, client/src/components/atoms/BottomBtn/styled.tsx, client/src/components/modules/CheckListHeader/styled.tsx, client/src/components/modules/CheckableProduct/CheckableProduct.tsx, client/src/components/modules/CheckableProduct/styled.tsx, client/src/components/modules/ContainerHeader/styled.tsx, client/src/components/modules/Header/Header.tsx, client/src/components/modules/Header/styled.tsx, client/src/components/modules/ProductCard/ProductCard.tsx, client/src/components/modules/ProductCard/styled.tsx, client/src/components/modules/ToastModal/styled.tsx
- 글씨가 작아서 폰트 크기 수정함.
- 글자가 넘치면 생략하도록 스타일 수정
- resolve #117 
🔗 [링크](url)
=> fix: font 크기 수정 및 넘치는 글자 생략

client/src/commons/styles/Normalize.tsx, client/src/components/atoms/Input/Input.spec.tsx, client/src/components/atoms/Input/Input.tsx, client/src/components/atoms/Input/index.tsx, client/src/components/atoms/Input/styled.tsx, client/src/components/templates/SignUpContainer/SignUpContainer.spec.tsx, client/src/components/templates/SignUpContainer/SignUpContainer.tsx, client/src/components/templates/SignUpContainer/index.tsx, client/src/components/templates/SignUpContainer/styled.tsx, client/src/pages/signup/index.tsx
회원가입페이지를 구현하였습니다.
atom에 Input 컴포넌트를 생성하였습니다.
페이지의 height 100%로 맞추었습니다.
- resolve #127 
🔗 [링크](url)
=> feat: 회원가입 페이지 구현#127

client/src/commons/Context/Context.tsx, client/src/commons/styles/Normalize.tsx, client/src/components/atoms/Icon/Icon.tsx, client/src/components/atoms/Icon/styled.tsx, client/src/components/modules/CheckListHeader/CheckListHeader.tsx, client/src/components/modules/CheckableProduct/CheckableProduct.tsx, client/src/components/modules/ContainerHeader/ContainerHeader.tsx, client/src/components/modules/Header/Header.tsx, client/src/components/modules/OutOfStockProduct/OutOfStockProduct.tsx, client/src/components/modules/OutOfStockProduct/index.tsx, client/src/components/modules/OutOfStockProduct/styled.tsx, client/src/components/modules/ToastModal/ToastModal.tsx, client/src/components/modules/TotalPriceInfo/TotalPriceInfo.tsx, client/src/components/modules/TotalPriceInfo/index.tsx, client/src/components/modules/TotalPriceInfo/styled.tsx, client/src/components/templates/CheckListContainer/CheckListContainer.tsx, client/src/components/templates/OutOfStockContainer/OutOfStockContainer.tsx, client/src/components/templates/OutOfStockContainer/index.tsx, client/src/components/templates/OutOfStockContainer/styled.tsx, client/src/pages/cart/index.tsx, client/src/pages/index.tsx, client/src/utils/constants.tsx, client/src/utils/index.tsx, server/src/controllers/cart-controller.ts
- 품절인 상품 표시
- 총 금액 표시
- 주문하기 버튼 개발
**이슈**
유저 토큰으로 cart id를 초기화하는 로직이 필요합니다.
주문하기 버튼 width 조절이 필요합니다.
Layout footer 개발이 필요합니다.
- resolve #이슈넘버
🔗 [링크](url)
=> feat: 장바구니 페이지ui 개발 #119

client/src/commons/Context/Context.tsx, client/src/components/atoms/Icon/Icon.tsx, client/src/components/atoms/Icon/styled.tsx, client/src/components/modules/Header/Header.stories.tsx, client/src/components/modules/Header/Header.tsx, client/src/components/templates/CategoryContainer/CategoryContainer.tsx, client/src/components/templates/CheckListContainer/CheckListContainer.tsx, client/src/components/templates/OutOfStockContainer/OutOfStockContainer.tsx, client/src/components/templates/SlidableContainer/SlidableContainer.tsx, client/src/components/templates/TabViewContainer/TabViewContainer.tsx
- Icon right button onClick function nullable 하게 수정
- 동적 생성 컴포넌트 key값 지정
- resolve #이슈넘버
🔗 [링크](url)
=> Fix build error#137

shared/validate.ts
> 유효성검사를 위한 validate 파일 생성
- resolve #이슈넘버
🔗 [링크](url)
=> chore: 유효성검사

server/src/bulk-data/data/user.json, server/src/bulk-data/index.ts, server/src/controllers/auth-controller.ts, server/src/models/login-provider.ts, server/src/models/user.ts, shared/validate.ts
user 객체의 username, email
login_provider 객체의 email
그리고 email 회원 가입시 password
validation 체크 기능 추가했습니다.
- resolve #140
=> feat: user name, email, password validation 추가 #140

client/src/components/atoms/Input/Input.tsx, client/src/components/atoms/Input/styled.tsx, client/src/components/templates/SignInContainer/SignInContainer.tsx, client/src/components/templates/SignUpContainer/SignUpContainer.tsx, client/src/utils/validate.tsx, client/tsconfig.json
> 회원가입과 로그인시 프론트엔드부분에서 유효성검사를 진행해서 메시지를 띄워줍니다.
shared의 validate에서 regex를 가져오는데 로더가 필요하다는 메시지가 나와서 추후에 해결이 필요합니다.
- resolve #130 
🔗 [링크](url)
=> feat: 유효성 검사#130

client/src/commons/Context/Context.tsx, client/src/components/modules/ProductCard/ProductCard.tsx, client/src/components/modules/ToastModal/ToastModal.tsx, client/src/components/templates/SignInContainer/SignInContainer.tsx, client/src/components/templates/SignUpContainer/SignUpContainer.tsx, client/src/pages/_app.tsx, client/src/utils/cookie-manager.tsx, server/src/controllers/auth-controller.ts, server/src/controllers/cart-controller.ts, server/src/controllers/like-controller.ts, server/src/routers/cart-router.ts, server/src/routers/like-router.ts
- token을 이용한 api 호출
- token이 없는 경우 로그인 화면으로 전환 안내
- token을 확인하여 페이지 권한 설정
- email signup, login시 token과 expires 응답, cookie 저장
- resolve #149
=> Link token api#149

client/src/commons/Context/Context.tsx, client/src/components/atoms/LogOut/LogOut.tsx, client/src/components/templates/MenuNavContainer/MenuNavContainer.tsx, client/src/components/templates/SignInContainer/SignInContainer.tsx, client/src/components/templates/SignUpContainer/SignUpContainer.tsx, client/src/pages/index.tsx, client/src/pages/menu/index.tsx, server/src/controllers/auth-controller.ts, server/src/routers/auth-router.ts
- token 변경시 새로운 user context fetch
- user 정보에 따른 slidable container 이름 표시
- logout 구현
- isValidToken 을 통해 클라이언트에게 user정보 제공
- resolve #153
=> feat: token을 이용해 user 정보 context 관리 #153

client/src/components/modules/Footer/Footer.tsx, client/src/components/modules/Footer/styled.ts, client/src/components/templates/SignInContainer/SignInContainer.tsx, client/src/components/templates/SignUpContainer/SignUpContainer.tsx, client/src/utils/constants.tsx
푸터 구현
- resolve #158 
🔗 [링크](url)
=> feat: footer 구현#158

client/src/commons/styles/Normalize.tsx, client/src/components/atoms/LogOut/LogOut.tsx, client/src/components/atoms/LogOut/styled.tsx, client/src/components/modules/Footer/styled.ts, client/src/components/modules/ToastModal/styled.tsx, client/src/components/templates/CategoryNavContainer/CategoryNavContainer.tsx, client/src/components/templates/CategoryNavContainer/styled.tsx, client/src/components/templates/FavoriteContainer/FavoriteContainer.spec.tsx, client/src/components/templates/FavoriteContainer/FavoriteContainer.tsx, client/src/components/templates/FavoriteContainer/index.tsx, client/src/components/templates/FavoriteContainer/styled.tsx, client/src/components/templates/MenuNavContainer/MenuNavContainer.tsx, client/src/components/templates/MenuNavContainer/styled.tsx, client/src/components/templates/SignInContainer/styled.tsx, client/src/components/templates/SignUpContainer/styled.tsx, client/src/pages/favorite/index.tsx, client/src/pages/menu/index.tsx
- 찜목록 페이지를 구현했습니다.
- 일부 색상을 새로 조절했습니다.
- 꽉 안차는 페이지를 수정했습니다. (flex-grow: 1)
- resolve #160 
🔗 [링크](url)
=> feat: 찜목록 페이지#160

client/package.json, client/src/animates/FadeIn/FadeIn.tsx, client/src/animates/FadeIn/index.tsx, client/src/animates/ScaleIn/ScaleIn.tsx, client/src/animates/ScaleIn/index.tsx, client/src/animates/ScaleIn/styled.tsx, client/src/animates/index.tsx, client/src/components/modules/ProductCard/ProductCard.tsx, client/src/components/templates/CategoryContainer/CategoryContainer.tsx, client/src/components/templates/CheckListContainer/CheckListContainer.tsx, client/src/components/templates/OutOfStockContainer/OutOfStockContainer.tsx, client/src/components/templates/ProductsByCategoryContainer/ProductsByCategoryContainer.tsx, client/src/components/templates/SlidableContainer/SlidableContainer.tsx, client/src/pages/index.tsx, client/tsconfig.json, client/yarn.lock
- item fade-in, item scale-in 적용
- resolve #162
=> animate: item fade-in, item scale-in 적용 #162

client/src/components/templates/CategoryNavContainer/CategoryNavContainer.tsx, client/src/components/templates/CategoryNavContainer/styled.tsx, client/src/components/templates/SignUpContainer/styled.tsx, client/src/pages/menu/index.tsx
메뉴페이지 하위카테고리 생성
- resolve ##155
🔗 [링크](url)
=> feat: menu페이지에 하위카테고리

client/src/components/modules/OutOfStockProduct/styled.tsx, client/src/components/modules/ProductCard/ProductCard.tsx, client/src/components/modules/ProductCard/styled.tsx, client/src/components/modules/TotalPriceInfo/styled.tsx, client/src/components/templates/CheckListContainer/styled.tsx, server/src/config/constants.ts, server/src/controllers/auth-controller.ts
- 품절시 이미지 위에 품절 박스 표시
- token 만료 시간 2시간으로 설정
- 글로벌 스타일 변경에 따라 장바구니 스타일 수정
- resolve #174
=> Soldout imgmodal#174

client/src/commons/Context/Context.tsx, client/src/components/modules/ProductCard/ProductCard.tsx, client/src/components/templates/DynamicContainer/DynamicContainer.tsx, client/src/components/templates/DynamicContainer/index.tsx, client/src/components/templates/DynamicContainer/styled.tsx, client/src/pages/index.tsx
클릭 개수에 따른 동적 컨테이너 구현 
- resolve #178
=> feat: 클릭 개수에 따른 동적 컨테이너 구현 #178

client/src/components/templates/CategoryNavContainer/CategoryNavContainer.tsx, client/src/components/templates/CategoryNavContainer/styled.tsx
카테고리 선택시 선택한 카테고리 폰트두께 수정
- resolve #188 
🔗 [링크](url)
=> fix: 카테고리 선택시 폰트두께 수정

client/src/components/templates/ProductsByCategoryContainer/ProductsByCategoryContainer.tsx, client/src/components/templates/TabViewContainer/TabViewContainer.tsx, client/src/pages/categories/[id].tsx, client/src/pages/hotdeal/index.tsx, client/src/pages/index.tsx, client/src/utils/constants.tsx
HotdealPage 구현하고 카테고리 페이지에서 SlidableContainer와 MainContainer에 보여질 상품을 다르게 처리하였습니다.
=> feat: HotDealPage 구현 및 카테고리 페이지 상품 분기

client/src/components/modules/ProductCard/ProductCard.tsx, shared/.env.sample
찜한 목록에서 like 버튼 클릭시 상품이 사라지면서 다음 상품 like버튼이 잘못 표시되는 버그 수정
- resolve #193
=> Bug like page#193

client/src/components/atoms/FilterSelect/FilterSelect.tsx, client/src/components/atoms/FilterSelect/index.tsx, client/src/components/atoms/FilterSelect/styled.tsx, client/src/components/templates/ProductsByCategoryContainer/ProductsByCategoryContainer.tsx, client/src/pages/index.tsx, client/src/utils/constants.tsx, client/src/utils/item-filter.tsx, server/src/controllers/auth-controller.ts, server/src/controllers/product-controller.ts
- [client] 상품 filter 기능 및 select 박스 구현
- [server] product 조회시 clicks 속성도 제공
- [chore] 사용하지 않는 로그 제거
- resolve #195
=> Produt filter#195

client/src/components/modules/HistoryCard/HistoryCard.tsx, client/src/components/modules/HistoryCard/styled.tsx, client/src/components/templates/HistoryContainer/HistoryContainer.tsx, client/src/pages/cart/index.tsx, client/src/pages/history/index.tsx
- 주문 상세 내역 표시 #197
- 빈 아이템시 텅빈 페이지 표시
- resolve #197
=> Order details#197

client/src/commons/styles/Normalize.tsx, client/src/components/modules/Header/styled.tsx, client/src/components/modules/ProductCard/styled.tsx, client/src/components/templates/FetchableContainer/styled.tsx
refactor: 필요없는 media query 삭제 및 font-size, padding, margin 상대값 조정 #199
- resolve #199
=> refactor: 필요없는 media query 삭제 및 font-size, padding, margin 상대값 조정 #199
